import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#fcf9f8',
        surface: '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0edec',
        'surface-container-high': '#ebe7e7',
        'surface-container-highest': '#e5e2e1',
        'surface-dim': '#dcd9d9',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#40484f',
        outline: '#707880',
        'outline-variant': '#bfc7d0',
        primary: '#006493',
        'on-primary': '#ffffff',
        'primary-container': '#4d9fd6',
        'on-primary-container': '#00334e',
        secondary: '#3f6653',
        'on-secondary': '#ffffff',
        'secondary-container': '#beead1',
        'on-secondary-container': '#436b58',
        tertiary: '#815500',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#cd8a00',
        'on-tertiary-container': '#442b00',
        gold: '#E8A020',
        'on-tertiary-fixed': '#1a1100',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        condensed: ['"Barlow Condensed"', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '36px', letterSpacing: '0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '28px', fontWeight: '600' }],
        'ranking-number': ['20px', { lineHeight: '20px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        sm: '2px',
        DEFAULT: '4px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        full: '9999px',
      },
      spacing: {
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'container-margin': '16px',
        gutter: '12px',
      },
      keyframes: {
        slideUp: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
      },
      animation: {
        slideUp: 'slideUp 200ms ease-out',
      },
    },
  },
} satisfies Config
